// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pkg/api/v1/p2p/pex.proto

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package p2p

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PexAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PexAddress) Reset() {
	*x = PexAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PexAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PexAddress) ProtoMessage() {}

func (x *PexAddress) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PexAddress.ProtoReflect.Descriptor instead.
func (*PexAddress) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_p2p_pex_proto_rawDescGZIP(), []int{0}
}

func (x *PexAddress) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PexRequest) Reset() {
	*x = PexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PexRequest) ProtoMessage() {}

func (x *PexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PexRequest.ProtoReflect.Descriptor instead.
func (*PexRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_p2p_pex_proto_rawDescGZIP(), []int{1}
}

type PexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses []*PexAddress `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *PexResponse) Reset() {
	*x = PexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PexResponse) ProtoMessage() {}

func (x *PexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PexResponse.ProtoReflect.Descriptor instead.
func (*PexResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_p2p_pex_proto_rawDescGZIP(), []int{2}
}

func (x *PexResponse) GetAddresses() []*PexAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type PexMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Sum:
	//	*PexMessage_PexRequest
	//	*PexMessage_PexResponse
	Sum isPexMessage_Sum `protobuf_oneof:"sum"`
}

func (x *PexMessage) Reset() {
	*x = PexMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PexMessage) ProtoMessage() {}

func (x *PexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_p2p_pex_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PexMessage.ProtoReflect.Descriptor instead.
func (*PexMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_p2p_pex_proto_rawDescGZIP(), []int{3}
}

func (m *PexMessage) GetSum() isPexMessage_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (x *PexMessage) GetPexRequest() *PexRequest {
	if x, ok := x.GetSum().(*PexMessage_PexRequest); ok {
		return x.PexRequest
	}
	return nil
}

func (x *PexMessage) GetPexResponse() *PexResponse {
	if x, ok := x.GetSum().(*PexMessage_PexResponse); ok {
		return x.PexResponse
	}
	return nil
}

type isPexMessage_Sum interface {
	isPexMessage_Sum()
}

type PexMessage_PexRequest struct {
	PexRequest *PexRequest `protobuf:"bytes,3,opt,name=pex_request,json=pexRequest,proto3,oneof"`
}

type PexMessage_PexResponse struct {
	PexResponse *PexResponse `protobuf:"bytes,4,opt,name=pex_response,json=pexResponse,proto3,oneof"`
}

func (*PexMessage_PexRequest) isPexMessage_Sum() {}

func (*PexMessage_PexResponse) isPexMessage_Sum() {}

var File_pkg_api_v1_p2p_pex_proto protoreflect.FileDescriptor

var file_pkg_api_v1_p2p_pex_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x32, 0x70,
	0x2f, 0x70, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x76, 0x31, 0x2e, 0x70,
	0x32, 0x70, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x0a, 0x50, 0x65, 0x78, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xe2, 0xde, 0x1f, 0x03, 0x55, 0x52, 0x4c, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x22, 0x0c, 0x0a,
	0x0a, 0x50, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x0b, 0x50,
	0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x50, 0x65, 0x78, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x0a, 0x50, 0x65, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x35, 0x0a, 0x0b, 0x70, 0x65, 0x78, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x32, 0x70, 0x2e,
	0x50, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x65,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x70, 0x65, 0x78, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x50, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x4a,
	0x04, 0x08, 0x02, 0x10, 0x03, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x68, 0x6f, 0x6a, 0x70, 0x75, 0x72, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x32, 0x70,
	0x3b, 0x70, 0x32, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_v1_p2p_pex_proto_rawDescOnce sync.Once
	file_pkg_api_v1_p2p_pex_proto_rawDescData = file_pkg_api_v1_p2p_pex_proto_rawDesc
)

func file_pkg_api_v1_p2p_pex_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_p2p_pex_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_p2p_pex_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_v1_p2p_pex_proto_rawDescData)
	})
	return file_pkg_api_v1_p2p_pex_proto_rawDescData
}

var file_pkg_api_v1_p2p_pex_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_v1_p2p_pex_proto_goTypes = []interface{}{
	(*PexAddress)(nil),  // 0: v1.p2p.PexAddress
	(*PexRequest)(nil),  // 1: v1.p2p.PexRequest
	(*PexResponse)(nil), // 2: v1.p2p.PexResponse
	(*PexMessage)(nil),  // 3: v1.p2p.PexMessage
}
var file_pkg_api_v1_p2p_pex_proto_depIdxs = []int32{
	0, // 0: v1.p2p.PexResponse.addresses:type_name -> v1.p2p.PexAddress
	1, // 1: v1.p2p.PexMessage.pex_request:type_name -> v1.p2p.PexRequest
	2, // 2: v1.p2p.PexMessage.pex_response:type_name -> v1.p2p.PexResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_p2p_pex_proto_init() }
func file_pkg_api_v1_p2p_pex_proto_init() {
	if File_pkg_api_v1_p2p_pex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_v1_p2p_pex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PexAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_p2p_pex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_p2p_pex_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_p2p_pex_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PexMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_api_v1_p2p_pex_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*PexMessage_PexRequest)(nil),
		(*PexMessage_PexResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_v1_p2p_pex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_v1_p2p_pex_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_p2p_pex_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_p2p_pex_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_p2p_pex_proto = out.File
	file_pkg_api_v1_p2p_pex_proto_rawDesc = nil
	file_pkg_api_v1_p2p_pex_proto_goTypes = nil
	file_pkg_api_v1_p2p_pex_proto_depIdxs = nil
}
